all: g++ task01.cpp -o task01.out
 ./task01.out 
 g++ task02.cpp -o task02.out ./task02.out
 g++ task03.cpp -o task03.out
 ./task03.out
 g++ task04.cpp -o task04.out ./task04.out
 g++ task05.cpp -o task05.out
 ./task05.out
 g++ task06.cpp -o task06.out ./task06.out
clean: rm task01.out
 rm task02.out
 rm task03.out 
  rm task04.out 
 rm task05.out
  rm task06.out